
 ### 오류(Error) 와 예외(Exception)

오류 : 시스템에서 비정상적인 상황이 생겼을 때 발생한다.
 즉 프로그램에서 컨트롤 할 수 없는 심각한 오류로 개발자의 프로그램에서 
 발생하지 않는 오류이기 때문에 미리 예측하여 처리할 수 가 없다 
  
 - 💀 에러 `Error` - 해결 불가능한 문제
    - 회사에 가다가 총에 맞아 죽음
        - 회사에 죽어도 *(죽었으니까)*  못 감
    - 무한루프, 메모리 한도 초과, 스택오버플로우 등…
        - 일반적으로 시스템 레벨의 문제


예외: 개발자가 구현한 로직에서 발생하는 오류 들이다.
 즉 발생할 상황을 미리 예측하여 처리할 수 있다.
  즉 예외는 개발자가 처리할 수 있기 때문에 예외를 구분하고 그에 따른 처리 방법을 구축 해야 한다.
  
  - 예외 `Exception`  - 대비하여 해결할 수 있는 문제
    - 가려던 출근길이 공사로 막힘, 지하철 운행 중단, 스텝이 꼬여 넘어짐
        - 대책을 마련해두면 회사에 갈 수 있음
    - 읽어오려는 파일이 없음, 배열의 길이 너머로 접근…

 
 정의 : 프로그램이 실행시 발생할 수 있는 예외의 발생에 대비하여 코드를 작성

목적: 프로그램의 비정상적인 종료를 막고 정상적인 실행 상태를 유지하는 것

		try {
			예외가 발생할 수 있는 코드 부분
		} catch(처리할 예외 타입1 e1) {
		    try 블록 안에서 예외1가 발생했을 때 예외를 처리하는 부분
		} catch(처리할 예외 타입2 e2) {
			    try 블록 안에서 예외2가 발생했을 때 예외를 처리하는 부분
		} catch(Exception e) {
			    try 블록 안에서 예외가 발생했을 때 예외를 처리하는 부분
		}
		try 블록에는 예외가 발생할 가능성이 있는 코드를 작성한다. 
		만약 try 블록 안에서 예외가 발생하면 바로 catch 블록이 수행된다.catch 문의 괄호 안에 쓰는 예외 타입은 예외 상황에 따라 달라진다.
		
		하나의 try 블록 다음에는 여러 종류의 예외를 처리할 수 있도록 하나 이상의 catch 블록이 올 수 있으며,
		 이 중 발생한 예외의 종류와 일치하는 단 한 개의 catch 블록만 수행된다.
		모든 예외 클래스는 Exception 클래스의 하위 클래스이므로 catch 블록의 괄호 안에 Exception 클래스 타입의 참조 변수를 선언해 놓으면 어떤 종류의
		 예외가 발생하더라도 이 catch 블록에 의해서 처리된다.
		가장 최상위 클래스인 Exception 클래스는 가장 마지막 블록에 위치해야 한다.
		
		
		
		- Unchecked Exception
    	- `RuntimeException` 의 하위 클래스들
    	- 개발자의 실수에 의해 발생할 수 있는 예외들
        - 걸어가다가 스텝이 꼬임
        - null 체크, 배열 등의 범위 벗어남, 0으로 나눔 등…
    	- 아래에서 배울 예외처리가 필수는 아님 *(실수를 안 하면 되므로)*
    	
		- Checked Exception
    	- 기타 예외들
    	- 주로 외적 요인으로 발생
        - 지하철 운행중단
    	- 발생 가능한 부분에는 반드시 예외처리해야 함 *(곧 배울 것)*
        - 처리하지 않을 시 컴파일 단계에서 반려
            - 지하철을 타는 코드의 경우 대안 마련해야 함
		
		
### 에러나 예외가 발생하면 프로그램이 종료됨

- 예외를 아래의 방법으로 예외처리 했을 경우 프로그램이 종료 안되게 할 수 있음 
		
		
		
- `getMessage` - 예외에 대한 간략 정보 문자열로 반환
- `printStackTrace` - 에러의 종류, 발생위치, 전반 단계 *(호출스택)* 출력
    - 디버깅에 매우 유용함
	
### `finally` 문
- 예외 발생 여부에 상관없이 반드시 실행할 코드
  - 데이터베이스 연결을 열어 작업한 뒤 닫아줄 때 등에 사용
	